apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: app-subscription
  namespace: default
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: app/manifests
spec:
  channel: application/app-channel
  placement:
    placementRef:
      name: app-placement
      kind: Placement
      namespace: application
