apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: application
  labels:
    app: appconfig
data:
  deployment.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      namespace: application
      name: hello-deployment
      labels:
        app: hello
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: hello
      template:
        metadata:
          labels:
            app: hello
        spec:
          serviceAccountName: my-sa
          containers:
            - name: hello
              image: busybox
              command: ["sh", "-c", 'echo "Hello, Kubernetes!" && sleep 3600']
