apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: app-channel
  namespace: application
spec:
  type: Git
  pathname: https://github.com/bbalakriz/acm-app-failover-deployment/deployment.yaml
