apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: app-subscription
  namespace: application
spec:
  channel: application/app-channel
  placement:
    placementRef:
      name: app-placement
  packageFilter:
    labelSelector:
      matchLabels:
        app: hello
